// CONFIG
export const SET_CONFIG = "SET_CONFIG";
export const SHOW_CONFIG = "SHOW_CONFIG";

// COUNT
export const ADD_COUNT_CARS = "ADD_COUNT_CARS";
export const ADD_COUNT_MOTORCYCLES = "ADD_COUNT_MOTORCYCLES";
export const REMOVE_COUNT_CARS = "REMOVE_COUNT_CARS";
export const REMOVE_COUNT_MOTORCYLES = "REMOVE_COUNT_MOTORCYLES";

// VEHICLE
export const ADD_VEHICLE = "ADD_VEHICLE";
export const REMOVE_VEHICLE = "REMOVE_VEHICLE";

// HISTORY
export const ADD_HISTORY_CARS = "ADD_HISTORY_CARS";
export const ADD_HISTORY_MOTORCYCLES = "ADD_HISTORY_MOTORCYCLES";
export const SHOW_HISTORY = "SHOW_HISTORY";
export const HIDE_HISTORY = "HIDE_HISTORY";
